---
name: Mundana
description: Mundana is a free Jekyll theme for awesome people like you, Medium like.
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: wowthemesnet@gmail.com
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  Leo:
    name: Leo
    site: https://www.leopuentes.me
    avatar: "/assets/images/avatar1.jpg"
    bio: Hi, I am Sal, the author of Mundana, the theme you're currently previewing.
      I hope you like it!
    email: elsermillonario@gmail.com
    twitter: https://twitter.com/elsermillonario
    facebook: https://www.facebook.com/elsermillonarioo
    instagram: https://www.instagram.com/elsermillonario
    tikTok: https://bit.ly/tiktokelsermillonario
    youtube: https://www.youtube.com/c/ElSerMillonario
  
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: Leo
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
